image: casah347rms/ros-foxy-base:latest

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - echo "Building..."
    - rm -rf /ros2 && mkdir -p /ros2/src
    - git clone git@fornat1.jpl.nasa.gov:casah/rosx/casah_msgs.git /ros2/src/casah_msgs
    - cd ..
    - cp -r dispatcher /ros2/src
    - cd /ros2
    - colcon build 

deploy:
  stage: deploy
  only:
    - master
  script:
    - echo "Deploying..."
    - mkdir -p build
    - cd build
    - cmake -DBUILD=OFF ..
    - make tag
