workspace: .
config: offline
nodes:

  - name: arm
    namespace: /arm
    node_name: arm
    cmd: ros2 launch install/bringup/share/bringup/launch/arm.py
    start_checked: true

  - name: commander
    namespace: /commander
    node_name: commander
    cmd: ros2 run commander commander
    start_checked: true
    stop_tmux_cmd: "C-D"


scripts:
    - name: kst
      cmd: kst2 &
      row: 0
      column: 1
      use_terminal: false
